spring.application.name=restaurant-backend
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/app-restaurant
spring.datasource.username=postgres
spring.datasource.password=54321
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway - COMPLETE CONFIGURATION
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



# Logging
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG


file.allowed-mime-types=image/jpeg,image/png,image/jpg
file.upload-dir=./uploads

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Allow case-insensitive Enum values
spring.jackson.mapper.accept-case-insensitive-enums=true

# Customizing the Swagger UI path (Default: /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html
# Customizing the OpenAPI spec path (Default: /v3/api-docs)
springdoc.api-docs.path=/api-docs

#logging configuration
logging.level.root=INFO
logging.level.org.springframework=DEBUG


