spring.application.name=restaurant-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=postgres
spring.datasource.password=54321
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


file.allowed-mime-types=image/jpeg,image/png,image/jpg
file.upload-dir=./uploads

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Allow case-insensitive Enum values
spring.jackson.mapper.accept-case-insensitive-enums=true


